name: Cypress Tests

on: [push]

jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout api repo
        uses: actions/checkout@v2
	with:
	  repository: ECE493Group13/api
	  path: api
          python-version: 3.8
	  make: serve

      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
